name: Release

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - name: zip
        run: zip -r cloth_physical_properties_compensation.zip *.py
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          files: |
            *.zip
